CRITICAL - 2022-01-26 03:49:52 --> Undefined property: CodeIgniter\View\View::$db
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\print.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 14)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('print', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(514): view('print')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Print()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 03:51:35 --> Undefined property: CodeIgniter\View\View::$db
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\print.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 14)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('print', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(514): view('print')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Print()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 03:52:40 --> Undefined property: CodeIgniter\View\View::$db
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\print.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 14)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('print', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(514): view('print')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Print()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 03:56:34 --> Undefined property: CodeIgniter\View\View::$db
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\print.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 14)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('print', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(514): view('print')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Print()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 03:58:57 --> Array to string conversion
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\print.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string...', 'C:\\xampp\\htdocs...', 18)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('print', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(514): view('print')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Print()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 09:06:41 --> Undefined array key "user_id"
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(98): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 98)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 09:07:47 --> CodeIgniter\BaseModel::transformDataToArray(): Return value must be of type array, string returned
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(735): CodeIgniter\BaseModel->transformDataToArray('Add to Cart', 'insert')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert('Add to Cart', false)
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(687): CodeIgniter\Model->insert('Add to Cart', false)
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(162): CodeIgniter\BaseModel->save('Add to Cart')
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-01-26 09:09:31 --> Undefined variable $session1
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(159): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 159)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 09:09:47 --> Undefined variable $session1
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(160): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 160)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 09:09:59 --> There is no data to insert.
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(163): CodeIgniter\BaseModel->save(Array)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-01-26 09:11:21 --> Undefined property: CodeIgniter\View\View::$request
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(161): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 161)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 09:24:34 --> Undefined variable $fashion_id
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(159): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 159)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 09:25:12 --> Undefined variable $fashion_item
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(160): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 160)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 09:26:10 --> CodeIgniter\BaseModel::transformDataToArray(): Return value must be of type array, bool returned
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(735): CodeIgniter\BaseModel->transformDataToArray(true, 'insert')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert(true, false)
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(687): CodeIgniter\Model->insert(true, false)
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(167): CodeIgniter\BaseModel->save(true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-01-26 09:34:11 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`fashion_item`, `unit_price`, `quantity`, `total_price`,`created_at`) VALUES ('1' at line 1
CRITICAL - 2022-01-26 09:34:11 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`fashion_item`, `unit_price`, `quantity`, `total_price`,`created_at`) VALUES ('1' at line 1
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(166): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...')
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-01-26 09:35:30 --> Unknown column '4' in 'field list'
CRITICAL - 2022-01-26 09:35:30 --> Unknown column '4' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(166): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...')
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-01-26 09:36:42 --> Unknown column '4' in 'field list'
CRITICAL - 2022-01-26 09:36:42 --> Unknown column '4' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(166): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...')
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-01-26 09:38:35 --> Unknown column '4' in 'field list'
CRITICAL - 2022-01-26 09:38:35 --> Unknown column '4' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(166): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...')
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-01-26 09:39:27 --> Unknown column '4' in 'field list'
CRITICAL - 2022-01-26 09:39:27 --> Unknown column '4' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(166): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...')
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-01-26 09:41:20 --> Unknown column '4' in 'field list'
CRITICAL - 2022-01-26 09:41:20 --> Unknown column '4' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(166): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...')
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-01-26 10:14:53 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:14:53 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 10:15:22 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:15:22 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 10:16:07 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:16:07 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 10:17:01 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:17:01 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 10:21:42 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:21:42 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 10:24:30 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:24:30 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 10:28:29 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:28:29 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 10:29:21 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:29:21 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 10:48:42 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:48:42 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('UPDATE `cart` S...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cart` S...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cart` S...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2482): CodeIgniter\Database\BaseConnection->query('UPDATE `cart` S...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(326): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(917): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(718): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(683): CodeIgniter\Model->update('7', Array)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 10:50:34 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:50:34 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('UPDATE `cart` S...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cart` S...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cart` S...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2482): CodeIgniter\Database\BaseConnection->query('UPDATE `cart` S...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(326): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(917): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(718): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(683): CodeIgniter\Model->update('7', Array)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 10:51:30 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:51:30 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('UPDATE `cart` S...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cart` S...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cart` S...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2482): CodeIgniter\Database\BaseConnection->query('UPDATE `cart` S...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(326): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(917): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(718): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(683): CodeIgniter\Model->update('7', Array)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 10:52:05 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:52:05 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('UPDATE `cart` S...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cart` S...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cart` S...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2482): CodeIgniter\Database\BaseConnection->query('UPDATE `cart` S...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(326): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(917): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(718): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(683): CodeIgniter\Model->update('7', Array)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 10:56:52 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 10:56:52 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-01-26 11:26:32 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 11:26:32 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-01-26 11:28:42 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-01-26 11:28:42 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('UPDATE `cart` S...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cart` S...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cart` S...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseBuilder.php(2482): CodeIgniter\Database\BaseConnection->query('UPDATE `cart` S...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(326): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(917): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Model.php(718): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\BaseModel.php(683): CodeIgniter\Model->update('7', Array)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(395): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2022-01-26 11:34:48 --> Class "App\Models\Cart1Model" not found
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->ProcessCart1()
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#5 {main}
ERROR - 2022-01-26 11:56:34 --> Unknown column 'total_price' in 'field list'
CRITICAL - 2022-01-26 11:56:34 --> Unknown column 'total_price' in 'field list'
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `ca...')
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\cart1.php(187): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...')
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('cart1', Array, true)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(387): view('cart1')
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Cart1()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#10 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-01-26 12:44:43 --> Undefined property: CodeIgniter\View\View::$db
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\print.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 30)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('print', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(527): view('print')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Print()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 12:48:44 --> Undefined property: CodeIgniter\View\View::$db
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\print.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 31)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('print', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(527): view('print')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Print()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 12:51:41 --> Object of class CodeIgniter\Database\MySQLi\Connection could not be converted to string
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include()
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('print', Array, true)
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(527): view('print')
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Print()
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-01-26 13:10:43 --> Undefined variable $total
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\print.php(57): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 57)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('print', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(527): view('print')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Print()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-26 13:13:58 --> Undefined variable $total
#0 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Views\print.php(74): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 74)
#1 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Common.php(1271): CodeIgniter\View\View->render('print', Array, true)
#4 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\app\Controllers\Cloth.php(527): view('print')
#5 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(928): App\Controllers\Cloth->Print()
#6 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cloth))
#7 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CodeIgniter4\CodeIgniter4\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
